// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheGameServer.Data;

#nullable disable

namespace TheGameServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508100642_AddAIPlayerSupport")]
    partial class AddAIPlayerSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheGameServer.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("TheGameServer.Models.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAI")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpectator")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("ReplacedByAI")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("TheGameServer.Models.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("GameDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPerfectGame")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalCardsRemaining")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("TheGameServer.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomRules")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GamePhase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsExpertMode")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("TheGameServer.Models.GameState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AscendingPile1")
                        .HasColumnType("integer");

                    b.Property<int>("AscendingPile2")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DescendingPile1")
                        .HasColumnType("integer");

                    b.Property<int>("DescendingPile2")
                        .HasColumnType("integer");

                    b.Property<string>("DrawPileCards")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayedCardsCount")
                        .HasColumnType("integer");

                    b.Property<string>("UndoSnapshotJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("TheGameServer.Models.PlayerGameStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardsInHand")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameResultId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PlayTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasReplacedByAI")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameResultId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("TheGameServer.Models.PlayerHand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cards")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerHands");
                });

            modelBuilder.Entity("TheGameServer.Models.PlayerStatistics", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AIAssistedGames")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRemainingCards")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("BestScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PerfectGames")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGames")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPlayTimeMinutes")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("TheGameServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAI")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TheGameServer.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("TheGameServer.Models.ChatMessage", b =>
                {
                    b.HasOne("TheGameServer.Models.GameSession", "GameSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGameServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheGameServer.Models.GamePlayer", b =>
                {
                    b.HasOne("TheGameServer.Models.GameSession", "GameSession")
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGameServer.Models.User", "User")
                        .WithMany("GamePlayers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheGameServer.Models.GameResult", b =>
                {
                    b.HasOne("TheGameServer.Models.GameSession", "GameSession")
                        .WithOne("Result")
                        .HasForeignKey("TheGameServer.Models.GameResult", "GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("TheGameServer.Models.GameSession", b =>
                {
                    b.HasOne("TheGameServer.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TheGameServer.Models.GameState", b =>
                {
                    b.HasOne("TheGameServer.Models.GameSession", "GameSession")
                        .WithOne("State")
                        .HasForeignKey("TheGameServer.Models.GameState", "GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TheGameServer.Models.MoveHistoryEntry", "MoveHistory", b1 =>
                        {
                            b1.Property<Guid>("GameStateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("PlayerUsername")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GameStateId", "Id");

                            b1.ToTable("GameStates");

                            b1.ToJson("MoveHistory");

                            b1.WithOwner()
                                .HasForeignKey("GameStateId");

                            b1.OwnsMany("TheGameServer.Models.MoveHistoryPlay", "Plays", b2 =>
                                {
                                    b2.Property<Guid>("MoveHistoryEntryGameStateId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MoveHistoryEntryId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Card")
                                        .HasColumnType("integer");

                                    b2.Property<int>("PileSlot")
                                        .HasColumnType("integer");

                                    b2.HasKey("MoveHistoryEntryGameStateId", "MoveHistoryEntryId", "Id");

                                    b2.ToTable("GameStates");

                                    b2.WithOwner()
                                        .HasForeignKey("MoveHistoryEntryGameStateId", "MoveHistoryEntryId");
                                });

                            b1.Navigation("Plays");
                        });

                    b.Navigation("GameSession");

                    b.Navigation("MoveHistory");
                });

            modelBuilder.Entity("TheGameServer.Models.PlayerGameStat", b =>
                {
                    b.HasOne("TheGameServer.Models.GameResult", "GameResult")
                        .WithMany("PlayerStats")
                        .HasForeignKey("GameResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGameServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameResult");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheGameServer.Models.PlayerHand", b =>
                {
                    b.HasOne("TheGameServer.Models.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheGameServer.Models.GamePlayer", "Player")
                        .WithOne("Hand")
                        .HasForeignKey("TheGameServer.Models.PlayerHand", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TheGameServer.Models.PlayerStatistics", b =>
                {
                    b.HasOne("TheGameServer.Models.User", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("TheGameServer.Models.PlayerStatistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheGameServer.Models.UserSession", b =>
                {
                    b.HasOne("TheGameServer.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheGameServer.Models.GamePlayer", b =>
                {
                    b.Navigation("Hand");
                });

            modelBuilder.Entity("TheGameServer.Models.GameResult", b =>
                {
                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("TheGameServer.Models.GameSession", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Players");

                    b.Navigation("Result");

                    b.Navigation("State");
                });

            modelBuilder.Entity("TheGameServer.Models.User", b =>
                {
                    b.Navigation("GamePlayers");

                    b.Navigation("Sessions");

                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
